name: peerpool
description: Peerpool Mobile Application

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animator: ^2.0.2
  app_tracking_transparency: 2.0.2+1
  carousel_slider: ^4.1.1
  chips_choice: ^2.0.1
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.2
  device_info: ^2.0.3
  dio: ^4.0.0
  email_validator: "^2.1.16"
  file_picker: any
  firebase_analytics: any
  firebase_core: any
  firebase_crashlytics: ^3.0.4
  firebase_messaging: any
  firebase_remote_config: ^3.0.4
  firebase_storage: ^11.0.6
  flutter_animator: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  flutter_inappwebview: ^5.3.2
  flutter_phone_direct_caller: any
  fluttertoast: ^8.0.9
  geolocator: ^9.0.2
  google_nav_bar: ^5.0.6
  google_places_flutter: ^2.0.5
  http: any
  intl: any
  line_icons: ^2.0.0
  loading_indicator: ^3.0.3
  open_file: ^3.2.1
  package_info: ^0.4.3+2
  path_provider: ^2.0.11
  percent_indicator: ^3.4.0
  permission_handler: any
  pinput: any
  shared_preferences: any
  url_launcher: ^6.0.3
  web3dart: any

  flutter_native_splash: ^2.0.5 #native splash dependency
  mailer: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  fullscreen: true
  android_gravity: center
  ios_content_mode: center

  android_12:
    image: assets/logo.png
    color: "#FFFFFF"
    fullscreen: true
    android_gravity: center
    ios_content_mode: center

  web: false

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets: ["assets/"]

  fonts:
    - family: Lato Bold
      fonts:
        - asset: assets/fonts/Lato-Bold.ttf
    - family: Lato Regular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
    - family: Lato Italic
      fonts:
        - asset: assets/fonts/Lato-Italic.ttf
    - family: Lato Light
      fonts:
        - asset: assets/fonts/Lato-Light.ttf
    - family: Lato Thin
      fonts:
        - asset: assets/fonts/Lato-Thin.ttf